// Generated by `npm run artifacts`.

export type AboutMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const ABOUT_MEDIA: readonly AboutMedia[] = [
  { slug: "a1", src: "/about/a1-ca9c342a.webp", width: 1200, height: 1010 },
  { slug: "a10", src: "/about/a10-19fb74e8.webp", width: 1200, height: 800 },
  { slug: "a11", src: "/about/a11-8c8557aa.webp", width: 999, height: 988 },
  { slug: "a12", src: "/about/a12-188c18d5.webp", width: 800, height: 1200 },
  { slug: "a2", src: "/about/a2-f211756d.webp", width: 828, height: 1200 },
  { slug: "a3", src: "/about/a3-7e303b45.webp", width: 1200, height: 1097 },
  { slug: "a4", src: "/about/a4-267340a7.webp", width: 800, height: 1200 },
  { slug: "a5", src: "/about/a5-c9a8631b.webp", width: 800, height: 1200 },
  { slug: "a6", src: "/about/a6-145cdf16.webp", width: 1200, height: 960 },
  { slug: "a7", src: "/about/a7-a85f35e0.webp", width: 1200, height: 1084 },
  { slug: "a8", src: "/about/a8-c844cf84.webp", width: 800, height: 1200 },
  { slug: "a9", src: "/about/a9-b7524140.webp", width: 1200, height: 800 },
];
