// Generated by `npm run artifacts`. Do not edit by hand.
//
// Dimensions are read off the encoded file rather than typed, so the box the
// page reserves always matches the image that lands in it. Filenames carry a
// content hash, because Next's image optimiser caches by URL and a replaced
// picture under an old name keeps serving the old picture.

export type BlogTopMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const BLOG_TOP_MEDIA: readonly BlogTopMedia[] = [
  { slug: "bt1", src: "/blogtop/bt1-d6ce3b64.webp", width: 938, height: 1200 },
  { slug: "bt2", src: "/blogtop/bt2-5b8ca1a2.webp", width: 766, height: 1173 },
  { slug: "bt3", src: "/blogtop/bt3-d7d25480.webp", width: 902, height: 1157 },
];
