// Generated by `npm run artifacts`. Do not edit by hand.
//
// Dimensions are read off the encoded file rather than typed, so the box the
// page reserves always matches the image that lands in it. Filenames carry a
// content hash, because Next's image optimiser caches by URL and a replaced
// picture under an old name keeps serving the old picture.

export type CardMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
  /** CSS `object-position`: where the crop centres when the frame is a different shape. */
  readonly focus?: string;
};

export const CARD_MEDIA: readonly CardMedia[] = [
  { slug: "c1", src: "/process/c1-a7bcd774.webp", width: 1536, height: 1024 },
  { slug: "c2", src: "/process/c2-d574c59a.webp", width: 2000, height: 1334 },
  { slug: "c3", src: "/process/c3-231b42fb.webp", width: 1333, height: 2000, focus: "50% 55%" },
  { slug: "c4", src: "/process/c4-b04903ef.webp", width: 1333, height: 2000, focus: "50% 50%" },
];
