// Generated by `npm run artifacts`.

export type CardMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const CARD_MEDIA: readonly CardMedia[] = [
  { slug: "c1", src: "/process/c1-36e41933.webp", width: 1200, height: 800 },
  { slug: "c2", src: "/process/c2-846239bf.webp", width: 1200, height: 800 },
  { slug: "c3", src: "/process/c3-b42af8ed.webp", width: 1024, height: 1024 },
  { slug: "c4", src: "/process/c4-a4824981.webp", width: 1200, height: 675 },
];
