// Generated by `npm run artifacts`. Do not edit by hand.
//
// Dimensions are read off the encoded file rather than typed, so the box the
// page reserves always matches the image that lands in it. Filenames carry a
// content hash, because Next's image optimiser caches by URL and a replaced
// picture under an old name keeps serving the old picture.

export type ContactMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const CONTACT_MEDIA: readonly ContactMedia[] = [
  { slug: "c1", src: "/contact/c1-de4c46d6.webp", width: 1200, height: 1200 },
  { slug: "c2", src: "/contact/c2-c2906ba4.webp", width: 1049, height: 1200 },
  { slug: "c3", src: "/contact/c3-7048430e.webp", width: 1200, height: 800 },
  { slug: "c4", src: "/contact/c4-ce27b396.webp", width: 1200, height: 800 },
  { slug: "c5", src: "/contact/c5-efa77042.webp", width: 1200, height: 800 },
  { slug: "c6", src: "/contact/c6-aab543ee.webp", width: 1200, height: 1000 },
];
