// Generated by `npm run artifacts`.

export type FooterMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const FOOTER_MEDIA: readonly FooterMedia[] = [
  { slug: "f1", src: "/footer/f1-87ba18eb.webp", width: 900, height: 728 },
  { slug: "f2", src: "/footer/f2-5ba64e95.webp", width: 900, height: 748 },
  { slug: "f3", src: "/footer/f3-c60b621d.webp", width: 844, height: 900 },
  { slug: "f4", src: "/footer/f4-f0eec4f5.webp", width: 900, height: 688 },
];
