// Generated by `npm run artifacts`. Do not edit by hand.
//
// Dimensions are read off the encoded file rather than typed, so the box the
// page reserves always matches the image that lands in it. Filenames carry a
// content hash, because Next's image optimiser caches by URL and a replaced
// picture under an old name keeps serving the old picture.

export type FooterMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const FOOTER_MEDIA: readonly FooterMedia[] = [
  { slug: "f1", src: "/footer/f1-87ba18eb.webp", width: 900, height: 728 },
  { slug: "f2", src: "/footer/f2-5ba64e95.webp", width: 900, height: 748 },
  { slug: "f3", src: "/footer/f3-c60b621d.webp", width: 844, height: 900 },
  { slug: "f4", src: "/footer/f4-f0eec4f5.webp", width: 900, height: 688 },
];
