// Generated by `npm run artifacts`.

export type HeroMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const HERO_MEDIA: readonly HeroMedia[] = [
  { slug: "a1", src: "/landing/a1-28a1d50e.webp", width: 751, height: 800 },
  { slug: "a2", src: "/landing/a2-0e37afd4.webp", width: 737, height: 800 },
  { slug: "a3", src: "/landing/a3-bb51de32.webp", width: 741, height: 800 },
  { slug: "a4", src: "/landing/a4-8344dc66.webp", width: 684, height: 800 },
];
