// Generated by `npm run artifacts`. Do not edit by hand.
//
// Dimensions are read off the encoded file rather than typed, so the box the
// page reserves always matches the image that lands in it. Filenames carry a
// content hash, because Next's image optimiser caches by URL and a replaced
// picture under an old name keeps serving the old picture.

export type ImpactMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const IMPACT_MEDIA: readonly ImpactMedia[] = [
  { slug: "i1", src: "/impact/i1-95b5cf38.webp", width: 1600, height: 676 },
  { slug: "i2", src: "/impact/i2-e040620b.webp", width: 1452, height: 945 },
  { slug: "i3", src: "/impact/i3-91bf7f4a.webp", width: 1453, height: 942 },
  { slug: "i4", src: "/impact/i4-ff0af257.webp", width: 1450, height: 942 },
  { slug: "i5", src: "/impact/i5-713fcb2e.webp", width: 1536, height: 1024 },
];
