// Generated by `npm run artifacts`. Do not edit by hand.
//
// Dimensions are read off the encoded file rather than typed, so the box the
// page reserves always matches the image that lands in it. Filenames carry a
// content hash, because Next's image optimiser caches by URL and a replaced
// picture under an old name keeps serving the old picture.

export type ServiceDetailMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const SERVICE_DETAIL_MEDIA: readonly ServiceDetailMedia[] = [
  { slug: "ms1", src: "/service-detail/ms1-04ab370e.webp", width: 1122, height: 1402 },
  { slug: "ms2", src: "/service-detail/ms2-4f572627.webp", width: 1222, height: 1287 },
  { slug: "ms3", src: "/service-detail/ms3-536ac8ae.webp", width: 1122, height: 1402 },
  { slug: "ms4", src: "/service-detail/ms4-2e3e36e6.webp", width: 1122, height: 1402 },
  { slug: "ms5", src: "/service-detail/ms5-de8d436b.webp", width: 1122, height: 1402 },
  { slug: "ms6", src: "/service-detail/ms6-f4e6378a.webp", width: 1122, height: 1402 },
];
