// Generated by `npm run artifacts`. Do not edit by hand.
//
// Dimensions are read off the encoded file rather than typed, so the box the
// page reserves always matches the image that lands in it. Filenames carry a
// content hash, because Next's image optimiser caches by URL and a replaced
// picture under an old name keeps serving the old picture.

export type ServicesMedia = {
  readonly slug: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const SERVICES_MEDIA: readonly ServicesMedia[] = [
  { slug: "s1", src: "/services-art/s1-ad40a87d.webp", width: 981, height: 1296 },
  { slug: "s2", src: "/services-art/s2-21228e68.webp", width: 1206, height: 1015 },
  { slug: "s3", src: "/services-art/s3-aeb78334.webp", width: 1218, height: 1090 },
  { slug: "s4", src: "/services-art/s4-b129f78b.webp", width: 1214, height: 1059 },
];
